FROM ubuntu:24.04

ENV GH_RUNNER_VERSION=2.322.0

RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    tar \
    && add-apt-repository ppa:dotnet/backports \
    && apt-get update \
    && apt-get install -y dotnet-sdk-6.0

WORKDIR /runner

RUN useradd runner && chown -R runner:runner /runner

USER runner

RUN curl -o actions-runner-linux-x64-2.322.0.tar.gz -L https://github.com/actions/runner/releases/download/v${GH_RUNNER_VERSION}/actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz

RUN tar xzf ./actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz && \
    rm actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz

ENTRYPOINT ["./entrypoint.sh"]
