name: All Hands Deployment

on:
  workflow_dispatch:
  schedule:
    - cron: 0 19 * * *

jobs:
  fetch-latest-minor-version:
    runs-on: self-hosted
    steps:
      - name: Get latest tag from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: All-Hands-AI/OpenHands
      - name: Get latest tag
        id: latest-minor-tag
        run: |
          export LATEST_MINOR_TAG=$(git tag --list | sort -V | tail -1 | cut -d. -f-2)
          export APP_NAME=openhands-app
      - name: Checkout homelab
        uses: actions/checkout@v4
        with:
          repository: cilasbeltrame/homelab
          path: homelab
      - name: Deploy it into docker host
        run: |
          cd homelab
          .github/workflows/scripts/docker-deploy.sh $APP_NAME $LATEST_MINOR_TAG
      
